### ISSUE TITLE
Not an Issue: Visual Number in each circle?

### ISSUE THREAD

**Issue by Koops50** [NathanQuayle/visual-ticks#3]
Not really an issue, but I'm more of a visual learning when it comes to this (hence why I downloaded the plugin) I was wondering if we could add a toggle to show the number inside of the circle for each tick? 

So it would look something like this? 
![5cf2a6816c658a00a93690245c8254cd](https://github.com/NathanQuayle/visual-ticks/assets/171043903/009e03b6-b8d2-445a-aa1b-9147c1b5e71b)

**Comment by NathanQuayle** [comment]
This will go out with the next update. I'll try and start the update process with Runelite tonight.
